FROM hexpm/elixir:1.18.3-erlang-27.3.4-debian-bullseye-20250428-slim

RUN apt-get update -y && apt-get install -y --no-install-recommends \
  build-essential \
  git \
  curl \
  inotify-tools \
  ca-certificates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

ENV MIX_ENV=dev

CMD ["mix", "phx.server"]
